data:
  _target_: age.data.datamodule.GraphDataModule
  dataset_name: PROTEINS
  data_dir: ${oc.env:PROJECT_ROOT}/data/${nn.data.dataset_name}/raw/

  datasets:
    train:
      _target_: age.data.dataset.MyDataset

#    val:
#      - _target_: age.data.dataset.MyDataset

    test:
      - _target_: age.data.dataset.MyDataset

  gpus: ${train.trainer.gpus}

  num_workers:
    train: 8
    val: 4
    test: 4

  batch_size:
    train: 32
    val: 16
    test: 16

module:
  _target_: age.pl_modules.pl_module.MyLightningModule

  model:
    _target_: age.modules.baseline.GraphClassifier
    num_mlp_layers: 1
    hidden_dim: 64
    feature_dim: ???
    num_classes: ???
    output_dim: 64

  optimizer:
    #  Adam-oriented deep learning
    _target_: torch.optim.Adam
    #  These are all default parameters for the Adam optimizer
    lr: 0.001
    betas: [ 0.9, 0.999 ]
    eps: 1e-08
    weight_decay: 0

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
    T_0: 10
    T_mult: 2
    eta_min: 0 # min value for the lr
    last_epoch: -1
    verbose: False
